### ISSUE TITLE
NoSuchBeanDefinitionException Consumer<Message<?>> sftpConsumer

### ISSUE THREAD

**Issue by cachescrubber** [spring-cloud/spring-functions-catalog#2]
When using the `sftp-consumer`  module as a [dependency in a custom application](https://github.com/spring-cloud/stream-applications/blob/main/functions/consumer/sftp-consumer/README.adoc), a bean of type `Consumer<Message<?>> sftpConsumer` is not available. However, the `IntegrationFlow ftpOutboundFlow` is available for injection.

Spring Boot: 3.1.5
Stream Applications 4.0.0
JDK 17

Reproducer in https://github.com/cachescrubber/sftp-consumer-demo/tree/main

```
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'java.util.function.Consumer<org.springframework.messaging.Message<?>>' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier("sftpConsumer")}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1824)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1383)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:764)

```

**Comment by artembilan** [comment]
I have another idea how to avoid this problem, but it will be fixed already here in this project.
Stay tuned.
